/* Action Types */
export const FETCH_PRODUCTS = "FETCH_ALL_PRODUCTS";
export const FETCH_CATEGORIES = "FETCH_ALL_CATEGORIES";
export const FETCH_CURRENCIES = "FETCH_ALL_CURRENCIES";

export const CURRENCY_SELECTED = "CURRENCY_SELECTED";
